"""add ChatMessage model and extend ticket model

Revision ID: 00644f5a1945
Revises: 001
Create Date: 2025-12-28 19:08:41.734965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00644f5a1945'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.add_column('tickets', sa.Column('client_fingerprint', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('priority_score', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_tickets_client_fingerprint'), 'tickets', ['client_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_client_fingerprint'), table_name='tickets')
    op.drop_column('tickets', 'is_deleted')
    op.drop_column('tickets', 'priority_score')
    op.drop_column('tickets', 'client_fingerprint')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
