"""Add Article model, User role, and ChatMessage article reference

Revision ID: a8c6192d39ec
Revises: 00644f5a1945
Create Date: 2026-01-21 21:26:45.264561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c6192d39ec'
down_revision: Union[str, Sequence[str], None] = '00644f5a1945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('excerpt', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('inquiry_count', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_category'), 'articles', ['category'], unique=False)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_language'), 'articles', ['language'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.add_column('chat_messages', sa.Column('client_name', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('client_email', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('client_phone', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('referenced_article_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_messages_referenced_article_id'), 'chat_messages', ['referenced_article_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'articles', ['referenced_article_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_referenced_article_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'referenced_article_id')
    op.drop_column('chat_messages', 'client_phone')
    op.drop_column('chat_messages', 'client_email')
    op.drop_column('chat_messages', 'client_name')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_language'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_category'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
